### ISSUE TITLE
notification is not shown when i clicked the button add product , transaction is not performed how to resolved this problem. 

### ISSUE THREAD

**Issue by Ash1mi** [A4ANK/Fake-Product-Identification#6]

**Comment by Shivu00001** [comment]
It's  working Bro you  just follow the rules what they displayed  in github step by step like how they shown definately it works because iam too working on the same project by these procedures only 
ex: 1st open truffle file and WAC: truffle compile
 2nd step: open ganache add click on new worksheet
                 Then add truffle file project  click on restart button
3rd step: open meta mask add network  and chain, path
                     click import account and open ganache then add a privacy key
4th step: open truffle and WAC: truffle migrate
4th step: WAC: npm run dev
its open and click meta mask the add to connected site setting 
Then it completely works the project
